<?php

$min = 20000;
$max = 1000000;
$textbotlang = $schema->context('textbotlang');

$values = [
    'Cartstatus' => 'oncard',
    'CartDirect' => '@cart',
    'cardnumber' => '603700000000',
    'namecard' => $textbotlang['db_defaults']['namecardNotSet'],
    'Cartstatuspv' => 'offcardpv',
    'apinowpayment' => '0',
    'nowpaymentstatus' => 'offnowpayment',
    'digistatus' => 'offdigi',
    'statusSwapWallet' => 'offnSolutions',
    'statusaqayepardakht' => 'offaqayepardakht',
    'merchant_id_aqayepardakht' => '0',
    'minbalance' => '20000',
    'maxbalance' => '1000000',
    'marchent_tronseller' => '0',
    'walletaddress' => '0',
    'statustarnado' => 'offternado',
    'apiternado' => '0',
    // Legacy iranpay2 settings belong to CubePay, not the official Tronado API.
    'tronado_status' => 'offtronado',
    'tronado_api_key' => '0',
    'tronado_wallet_address' => '0',
    'tronado_ipn_signing_key' => '0',
    'tronado_min' => '20000',
    'tronado_max' => '1000000',
    'tronado_cashback' => '0',
    'tonpays_status' => 'offtonpays',
    'tonpays_api_key' => '0',
    'tonpays_min' => '20000',
    'tonpays_max' => '1000000',
    'feestatusternado' => 'offfeeternado',
    'feeternado' => '0',
    'chashbackcart' => '0',
    'chashbackstar' => '0',
    'chashbackperfect' => '0',
    'chashbackaqaypardokht' => '0',
    'chashbackiranpay1' => '0',
    'chashbackiranpay2' => '0',
    'chashbackiranpay3' => '0',
    'chashbackplisio' => '0',
    'chashbackzarinpal' => '0',
    'cashbacknowpayment' => '0',
    'checkpaycartfirst' => 'offpayverify',
    'zarinpalstatus' => 'offzarinpal',
    'zarinpal_payment_gate_enabled' => '1',
    'zarinpal_min_successful_payments' => '2',
    'merchant_zarinpal' => '0',
    'tetraminatorstatus' => 'offtetraminator',
    'tetraminator_apikey' => '0',
    'tetraminator_baseurl' => 'https://api.tetraminator.com/v1',
    'tetraminator_min' => '50000',
    'tetraminator_max' => '10000000',
    'tetraminator_label' => 'درگاه پرداخت ریالی',
    'uniquepaystatus' => 'offuniquepay',
    'uniquepay_token' => '0',
    'uniquepay_baseurl' => 'https://uniquepay.top',
    'uniquepay_label' => 'درگاه پرداخت یونیک‌پی',
    'minbalanceuniquepay' => $min,
    'maxbalanceuniquepay' => $max,
    'chashbackuniquepay' => '0',
    'statusiranpay3' => 'oniranpay3',
    'apiiranpay' => '0',
    'autoconfirmcart' => 'offauto',
    'statusstar' => '0',
    'statusnowpayment' => '0',
    'Exception_auto_cart' => '{}',
    'marchent_floypay' => '0',
    'minbalancecart' => $min,
    'maxbalancecart' => $max,
    'minbalancestar' => $min,
    'maxbalancestar' => $max,
    'minbalanceplisio' => $min,
    'maxbalanceplisio' => $max,
    'minbalancedigitaltron' => $min,
    'maxbalancedigitaltron' => $max,
    'minbalanceiranpay1' => $min,
    'maxbalanceiranpay1' => $max,
    'minbalanceiranpay2' => $min,
    'maxbalanceiranpay2' => $max,
    'minbalanceaqayepardakht' => $min,
    'maxbalanceaqayepardakht' => $max,
    'minbalancepaynotverify' => $min,
    'maxbalancepaynotverify' => $max,
    'minbalanceperfect' => $min,
    'maxbalanceperfect' => $max,
    'minbalancezarinpal' => $min,
    'maxbalancezarinpal' => $max,
    'minbalanceiranpay' => $min,
    'maxbalanceiranpay' => $max,
    'minbalancenowpayment' => $min,
    'maxbalancenowpayment' => $max,
    'helpcart' => '2',
    'helpaqayepardakht' => '2',
    'helpstar' => '2',
    'helpplisio' => '2',
    'helpiranpay1' => '2',
    'helpiranpay2' => '2',
    'helpiranpay3' => '2',
    'helpiranpay4' => '2',
    'apiiranpay4' => '0',
    'endpointiranpay4' => '0',
    'statusiranpay4' => 'offiranpay4',
    'minbalanceiranpay4' => '20000',
    'maxbalanceiranpay4' => '1000000',
    'dailylimitiranpay4' => '0',
    'chashbackiranpay4' => '0',
    'variza_status' => 'offvariza',
    'variza_api_token' => '0',
    'variza_webhook_secret' => '0',
    'minbalancevariza' => '20000',
    'maxbalancevariza' => '1000000',
    'chashbackvariza' => '0',
    'helpvariza' => '2',
    'helpperfectmony' => '2',
    'helpzarinpal' => '2',
    'helpnowpayment' => '2',
    'helpofflinearze' => '2',
];

$seed = [];
foreach ($values as $name => $value) {
    $seed[] = ['NamePay' => $name, 'ValuePay' => $value];
}

return [
    'create' => <<<SQL
        NamePay varchar(500) PRIMARY KEY NOT NULL,
        ValuePay TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL
        SQL,
    'seed' => $seed,
];
